/** Raw SQL queries for fetching database schema metadata */

/** All tables and views */
export const ALL_OBJECTS_QUERY = `
SELECT TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;
`;

/** All stored procedures and functions */
export const ALL_ROUTINES_QUERY = `
SELECT ROUTINE_NAME, ROUTINE_TYPE
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'dbo'
ORDER BY ROUTINE_NAME;
`;

/** All columns (bulk load) */
export const ALL_COLUMNS_QUERY = `
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE,
       CHARACTER_MAXIMUM_LENGTH, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME, ORDINAL_POSITION;
`;

/** Columns for a specific table/view */
export const TABLE_COLUMNS_QUERY = `
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE,
       CHARACTER_MAXIMUM_LENGTH, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = @tableName
ORDER BY ORDINAL_POSITION;
`;

/** SP/Function definition */
export const OBJECT_DEFINITION_QUERY = `
SELECT OBJECT_DEFINITION(OBJECT_ID(@objectName)) AS [definition];
`;

/** SP parameters */
export const SP_PARAMETERS_QUERY = `
SELECT PARAMETER_NAME, DATA_TYPE, PARAMETER_MODE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.PARAMETERS
WHERE SPECIFIC_SCHEMA = 'dbo' AND SPECIFIC_NAME = @spName
ORDER BY ORDINAL_POSITION;
`;
